server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bank_application
    username: ${USERNAME}
    password: ${PASSWORD}
  liquibase:
      change-log: db.changelog/db.changelog-master.yaml
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
fxratesapi:
  access:
    link: ${LINK}
    token: ${TOKEN}